### ISSUE TITLE
Cannot import @angular/common/http in ionic using @angular/common 4.1.3

### ISSUE THREAD

**Issue by ifigueroap** [Nodonisko/ionic-cache#75]
Hi, I'm developing a Ionic app, meant to target both iOS and Android. I just added the ionic-cache service to the application, and it was working OK in when using `ionic serve`

However, when deploying to an Android device I got an error:
```
Error: ./node_modules/ionic-cache/dist/cache.service.js
Module not found: Error: Can't resolve '@angular/common/http'
```

It seems the import is done in `cache.service.js`, line 92, where it has the line:

```
case 3:
        e_1 = _a.sent();
        return [4 /*yield*/, import('@angular/common/http')];
```
Actually I got it working by changing `'@angular/common/http'` to `'@angular/http'` as in the `case 2` of the switch statement...

The full commands and log are 

```
Running app-scripts build: --platform android --target cordova
[17:24:38]  build dev started ...
[17:24:38]  clean started ...
[17:24:38]  clean finished in 17 ms
[17:24:38]  copy started ...
[17:24:39]  deeplinks started ...
[17:24:39]  deeplinks finished in 578 ms
[17:24:39]  transpile started ...
[17:24:51]  transpile finished in 11.32 s
[17:24:51]  preprocess started ...
[17:24:51]  preprocess finished in 1 ms
[17:24:51]  webpack started ...
[17:24:51]  copy finished in 12.33 s
Error: ./node_modules/ionic-cache/dist/cache.service.js
Module not found: Error: Can't resolve '@angular/common/http' in '/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/ionic-cache/dist'
resolve '@angular/common/http' in '/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/ionic-cache/dist'
  Parsed request is a module
  using description file: /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/ionic-cache/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/ionic-cache/package.json (relative path: ./dist)
    resolve as module
      looking for modules in /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules
        using description file: /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/package.json (relative path: ./node_modules)
          using description file: /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/package.json (relative path: ./http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http.json doesn't exist
            as directory
              /Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http doesn't exist
[/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http]
[/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http.ts]
[/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http.js]
[/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http.json]
[/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@angular/common/http]
 @ ./node_modules/ionic-cache/dist/cache.service.js 92:45-75
 @ ./node_modules/ionic-cache/dist/cache.module.js
 @ ./node_modules/ionic-cache/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at new BuildError (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/ismael/Documents/Proyectos/barrio-puerto-mobile/barrio-puerto/node_modules/webpack/lib/Compiler.js:365:9)
MacBook-Pro-de-Ismael:barrio-puerto ismael$ npm install @angular/common/http
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@angular/common/http" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ismael/.npm/_logs/2018-05-03T20_27_58_791Z-debug.log
MacBook-Pro-de-Ismael:barrio-puerto ismael$
MacBook-Pro-de-Ismael:barrio-puerto ismael$
MacBook-Pro-de-Ismael:barrio-puerto ismael$ npm outdated
Package                            Current  Wanted  Latest  Location
@angular/common                      4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/compiler                    4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/compiler-cli                4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/core                        4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/forms                       4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/http                        4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/platform-browser            4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/platform-browser-dynamic    4.1.3   4.1.3   6.0.0  barrio-puerto
@angular/tsc-wrapped                 4.4.6   4.4.7   4.4.6  barrio-puerto
@ionic/app-scripts                   3.1.8   3.1.9   3.1.9  barrio-puerto
cordova-android                      7.0.0   7.0.0   7.1.0  barrio-puerto
cordova-plugin-facebook4            1.10.1  1.10.1   2.0.1  barrio-puerto
cordova-plugin-geolocation           2.4.3   2.4.3   4.0.1  barrio-puerto
cordova-plugin-splashscreen          4.1.0   4.1.0   5.0.2  barrio-puerto
phonegap-plugin-push                1.11.0  1.11.1   2.2.2  barrio-puerto
rxjs                                5.5.10  5.5.10   6.1.0  barrio-puerto
typescript                           2.3.4   2.3.4   2.8.3  barrio-puerto
zone.js                             0.8.12  0.8.12  0.8.26  barrio-puerto
```

**Comment by darthdie** [comment]
Thanks for opening an issue.

This has been fixed in commit 11c1ab0. We should be releasing a new NPM version in the next couple days.
